branches:
  only:
    - develop

language: node_js

sudo: false

node_js: 8

cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules

script:
  # - npm run lint:js
  # - npm run lint:md
  - npm run build:gh
